//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturers
    {
        public Manufacturers()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int ManufacturerID { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerWeb { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
