//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.PropertyValue = new HashSet<PropertyValue>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public int SubCategoryID { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string Series { get; set; }
        public string Model { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public string SeriesInfo { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ICollection<PropertyValue> PropertyValue { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
