//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.TypeFilter = new HashSet<TypeFilter>();
            this.TechSpecFilter = new HashSet<TechSpecFilter>();
            this.PropertyValue = new HashSet<PropertyValue>();
        }
    
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public Nullable<bool> IsType { get; set; }
        public Nullable<bool> IsTechSpec { get; set; }
    
        public virtual ICollection<TypeFilter> TypeFilter { get; set; }
        public virtual ICollection<TechSpecFilter> TechSpecFilter { get; set; }
        public virtual ICollection<PropertyValue> PropertyValue { get; set; }
    }
}
