//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public SubCategory()
        {
            this.Products = new HashSet<Products>();
            this.TypeFilter = new HashSet<TypeFilter>();
            this.TechSpecFilter = new HashSet<TechSpecFilter>();
        }
    
        public int SubCategoryID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string SubCategoryName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<TypeFilter> TypeFilter { get; set; }
        public virtual ICollection<TechSpecFilter> TechSpecFilter { get; set; }
    }
}
